"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['GitSyncApp.py']
DATA_FILES = ['Icon.png']
OPTIONS = {
    'argv_emulation': True,
    'packages': [
        'rumps',
        'fabric',
        'gitsync',
        #'fsevents',
        'yaml',
    ],
    'plist': {
        'LSUIElement': True,
    },
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    include_package_data=True,
    setup_requires=[
        'py2app'
    ],
)
